# Generated by Django 6.0.6 on 2026-06-28 19:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('author', models.CharField(max_length=250, verbose_name='Auteur')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Année de publication')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Image de couverture')),
                ('added_to_catalog', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout au catalogue")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-added_to_catalog'],
                'unique_together': {('title', 'author')},
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_status', models.CharField(choices=[('to_read', 'À lire'), ('reading', 'En cours'), ('finished', 'Terminé')], default='to_read', max_length=20, verbose_name='Statut de lecture')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favori')),
                ('is_read_later', models.BooleanField(default=False, verbose_name='À lire plus tard')),
                ('personal_note', models.TextField(blank=True, verbose_name='Note personnelle')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Évaluation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='books.book', verbose_name='Livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Livre utilisateur',
                'verbose_name_plural': 'Livres utilisateurs',
                'ordering': ['-added_date'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
